import { ArtCritique, PortfolioArtwork } from '../types';

export function generateCritiqueMarkdown(critique: ArtCritique): string {
  return `# ART DIRECTION & VLM CRITIQUE REPORT
**Artwork Title:** ${critique.artworkTitle}
**Master Overall Score:** ${critique.overallScore.toFixed(1)} / 10.0
**Gallery & Client Readiness:** ${critique.galleryReadiness}
**Style / Medium:** ${critique.artistStyle}
**Target Audience:** ${critique.targetContext}
**Intended Mood:** ${critique.intendedMood}
**Date:** ${new Date(critique.timestamp).toLocaleDateString()}

---

## 🏛️ EXECUTIVE SUMMARY
${critique.executiveSummary}

**Gallery & Art Director Perception:**
> "${critique.clientImpression}"

---

## 📊 PILLAR 1: COMPOSITION & VISUAL ARCHITECTURE
- **Score:** ${(critique.composition?.score || 0).toFixed(1)} / 10.0
- **Verdict:** ${critique.composition.headline}
- **Detailed Evaluation:**
${critique.composition.detailedAnalysis}

### Key Strengths:
${(critique.composition?.strengths || []).map((s) => `- ${s}`).join('\n')}

### Areas for Refinement:
${(critique.composition?.refinements || []).map((r) => `- ${r}`).join('\n')}

### Actionable Fix:
${critique.composition.actionableFix}

### Master Technique Tip:
💡 *${critique.composition.techniqueTip}*

---

## 🎨 PILLAR 2: LIGHTING & COLOR HARMONY
- **Score:** ${(critique.lightingAndColor?.score || 0).toFixed(1)} / 10.0
- **Verdict:** ${critique.lightingAndColor.headline}
- **Detailed Evaluation:**
${critique.lightingAndColor.detailedAnalysis}

### Key Strengths:
${(critique.lightingAndColor?.strengths || []).map((s) => `- ${s}`).join('\n')}

### Areas for Refinement:
${(critique.lightingAndColor?.refinements || []).map((r) => `- ${r}`).join('\n')}

### Actionable Fix:
${critique.lightingAndColor.actionableFix}

### Master Technique Tip:
💡 *${critique.lightingAndColor.techniqueTip}*

---

## 📐 PILLAR 3: ANATOMY & PERSPECTIVE SYSTEMS
- **Score:** ${(critique.anatomyAndPerspective?.score || 0).toFixed(1)} / 10.0
- **Verdict:** ${critique.anatomyAndPerspective.headline}
- **Detailed Evaluation:**
${critique.anatomyAndPerspective.detailedAnalysis}

### Key Strengths:
${(critique.anatomyAndPerspective?.strengths || []).map((s) => `- ${s}`).join('\n')}

### Areas for Refinement:
${(critique.anatomyAndPerspective?.refinements || []).map((r) => `- ${r}`).join('\n')}

### Actionable Fix:
${critique.anatomyAndPerspective.actionableFix}

### Master Technique Tip:
💡 *${critique.anatomyAndPerspective.techniqueTip}*

---

## 🎭 PILLAR 4: MOOD & NARRATIVE STORYTELLING
- **Score:** ${(critique.moodAndStorytelling?.score || 0).toFixed(1)} / 10.0
- **Verdict:** ${critique.moodAndStorytelling.headline}
- **Detailed Evaluation:**
${critique.moodAndStorytelling.detailedAnalysis}

### Key Strengths:
${(critique.moodAndStorytelling?.strengths || []).map((s) => `- ${s}`).join('\n')}

### Areas for Refinement:
${(critique.moodAndStorytelling?.refinements || []).map((r) => `- ${r}`).join('\n')}

### Actionable Fix:
${critique.moodAndStorytelling.actionableFix}

### Master Technique Tip:
💡 *${critique.moodAndStorytelling.techniqueTip}*

---

## ⚡ QUICK 5-MINUTE POLISH WINS
${(critique.quickWins || []).map((w, i) => `${i + 1}. [ ] ${w}`).join('\n')}

---

## 🎯 PORTFOLIO PRESENTATION STRATEGY
${(critique.portfolioRecommendations || []).map((p) => `- ${p}`).join('\n')}

---

## 🎨 EXTRACTED COLOR SCRIPT
| Role | Hex | Color Name | Theory Notes |
| :--- | :--- | :--- | :--- |
${critique.colorPalette
  .map(
    (c) => `| ${c.role} | \`${c.hex}\` | **${c.name}** | ${c.harmonyNotes} |`
  )
  .join('\n')}

*Generated by ArtCritique VLM Studio*
`;
}

export function downloadReportFile(critique: ArtCritique) {
  const md = generateCritiqueMarkdown(critique);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute(
    'download',
    `${critique.artworkTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-critique-report.md`
  );
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
